name: Generate Snake Game

# Controls when the action will run
on:
  schedule:
    # Runs every 6 hours
    - cron: "0 */6 * * *"

  workflow_dispatch:
    # Allows the workflow to be manually triggered from the Actions tab

# Sets up the job for generating the snake
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v3

      # Generates the snake animation and outputs a gif file
      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: imishangrover  # Replace 'your-username' with your GitHub username
          github_token: ${{ secrets.GITHUB_TOKEN }}

      # Automatically commits the generated snake to the repo
      - name: Commit and push snake animation
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Generated snake animation"
          file_pattern: dist/*
